Repository open-compass/VLMEvalKit, pull requests merged in 2025-05, with the labels that each got.

#979 [Model] Support NVILA & minor fix in LLaVA_OneVision
  .gitignore
  vlmeval/config.py
  vlmeval/vlm/__init__.py
  vlmeval/vlm/llava/llava.py
  vlmeval/vlm/vila.py
Labels: WIP

#963 Fix Qwen Omni when use audio in video
  vlmeval/config.py
  vlmeval/inference_video.py
  vlmeval/vlm/qwen2_vl/model.py
Labels: WIP

#919 [Benchmark] Support Screenspot, Screenspotv2, Screenspot_pro evaluation on Aguvis and InternVL
  .pre-commit-config.yaml
  requirements.txt
  vlmeval/config.py
  vlmeval/dataset/GUI/__init__.py
  vlmeval/dataset/GUI/screenspot.py
  vlmeval/dataset/GUI/screenspot_pro.py
  vlmeval/dataset/GUI/screenspot_v2.py
  vlmeval/dataset/__init__.py
  vlmeval/dataset/image_yorn.py
  vlmeval/vlm/__init__.py
  vlmeval/vlm/internvl/gui_template.yaml
  vlmeval/vlm/internvl/internvl_chat.py
  vlmeval/vlm/internvl/utils.py
  vlmeval/vlm/kimi_vl.py
  vlmeval/vlm/qwen2_vl/__init__.py
  vlmeval/vlm/qwen2_vl/model.py
  vlmeval/vlm/smolvlm.py
  vlmeval/vlm/vlm_r1.py
Labels: WIP

#1007 Add support for PhyX
  vlmeval/api/siliconflow.py
  vlmeval/config.py
  vlmeval/dataset/__init__.py
  vlmeval/dataset/image_vqa.py
  vlmeval/dataset/utils/judge_util.py
  vlmeval/dataset/utils/phyx.py
Labels: BUG

#1018 change position of visual tokens in MVBench
  vlmeval/config.py
  vlmeval/dataset/mlvu.py
  vlmeval/dataset/mvbench.py
  vlmeval/dataset/tempcompass.py
Labels: Pending
